version: '2'
services:
    connect-swagger:
        build:
            context: .
            dockerfile: swagger.connect.Dockerfile
        network_mode: "host"
        command: ["node", "connect-swagger.js"]
    connect-vanilla:
        build:
            context: .
            dockerfile: swagger.connect.Dockerfile
        network_mode: "host"
        command: ["node", "connect-vanilla.js"]
    express-swagger:
        build:
            context: .
            dockerfile: swagger.express.Dockerfile
        network_mode: "host"
        command: ["node", "express-swagger.js"]
    express-vanilla:
        build:
            context: .
            dockerfile: swagger.express.Dockerfile
        network_mode: "host"
        command: ["node", "express-vanilla.js"]
    restify-swagger:
        build:
            context: .
            dockerfile: swagger.restify.Dockerfile
        network_mode: "host"
        command: ["node", "restify-swagger.js"]
    restify-vanilla:
        build:
            context: .
            dockerfile: swagger.restify.Dockerfile
        network_mode: "host"
        command: ["node", "restify-vanilla.js"]
    hapi-swagger:
        build:
            context: .
            dockerfile: swagger.hapi.Dockerfile
        network_mode: "host"
        command: ["node", "hapi-swagger.js"]
    hapi-vanilla:
        build:
            context: .
            dockerfile: swagger.hapi.Dockerfile
        network_mode: "host"
        command: ["node", "hapi-vanilla.js"]
    sails-swagger:
        build:
            context: .
            dockerfile: swagger.sails.Dockerfile
        network_mode: "host"
        command: ["node", "sails-swagger.js", "--port", "10010", "--prod"]
        environment:
            NODE_ENV: production
    sails-vanilla:
        build:
            context: .
            dockerfile: swagger.sails.Dockerfile
        network_mode: "host"
        command: ["node", "sails-vanilla.js"]
    ab:
        image: jordi/ab
        command: 'bash -c "sleep 7; ab -n 100 -v 1 -k -c 1 http://localhost:10010/hello"'
        network_mode: "host"
